"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'
import _translation_card from './translation-card.bones.json'
import _user_list from './user-list.bones.json'

configureBoneyard({ "color": "#e5e5e5", "darkColor": "#2a2a2a", "animate": "pulse", "speed": "1.8s" })

registerBones({
  "translation-card": _translation_card,
  "user-list": _user_list,
})
