"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _translation_card from './translation-card.bones.json'

registerBones({
  "translation-card": _translation_card,
})
